# Bump version and tag on every PR branch merge back into main

name: Release

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Log github.event.head_commit.author.username
        run: echo "${{ github.event.head_commit.author.username }}"

      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          persist-credentials: false

      - name: Automated version bump
        id: version-bump
        uses: "phips28/gh-action-bump-version@v10.1.1"
        with:
          tag-prefix: "v"
          patch-wording: "fix,chore,docs,style,refactor,test,chore"
          minor-wording: "feat"
          major-wording: "BREAKING"
        env:
          # Needs to be a PAT in order to bypass branch protection
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
